firmware/urls.py
from django.urls import path

from . import views

app_name = 'firmware'

urlpatterns = [
    path('', views.ProductSearchView.as_view(discontinued=False), name='product-list'),
    path('discontinued-products', views.ProductSearchView.as_view(discontinued=True), name='discontinued-product-list'),

    path('newest', views.NewestView.as_view(), name='newest'),
    # path('lines', views.lines, name='lines'),
    # path('sites', views.BrandListView.as_view(), name='brand-list'),
    # path('brand/<int:pk>/', views.BrandDetailView.as_view(), name='brand-detail'),
    # path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),

    # path('subscribe/', views.subscribe, name='subscribe'),
    path("register", views.register_request, name="register"),
    path('login', views.login_page, name='login'),
    path('profile', views.profile, name='profile'),
    path('download/<int:id>', views.download_local_file, name='download'),
    path('products-search', views.products_search, name='products-search'),
    # path('thanks', views.thanks, name='thanks'),
    path('activate-user/<int:id>', views.activate_user, name='activate-user'),

]

firmwarefinder/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
     
    path('', include('firmware.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firmware/models.py
from django.db import models
from zipfile import ZipFile, BadZipFile
from django.core.files import File
from django.contrib.auth.models import User
from django.conf import settings
import os

import requests
from tempfile import TemporaryFile



class Brand(models.Model):
    """ The Brand of the product ie AMX BSS Crown
        base_url ie www.amx.com
        extra_path maybe used by the template ie /en-US/products/
    """
    name = models.CharField(max_length=200)
    base_url = models.CharField(max_length=200, unique=True)
    extra_path = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.base_url


class FG(models.Model):
    """ An FG number
        It is related to a specific product (and variations of that product color/ amp size)
        It is also related to all useable firmware versions
    """
    number = models.CharField(max_length=120, unique=True)

    def __str__(self):
        return f"{self.number}"


class AssociatedName(models.Model):
    """ The associated names, these are the names that products are referred to.
        For example:
        NMX-ENC-N2412A Encoder
        or N2412A
        or ENC-N2412A
        or n2400-svsi-hotfix-firmware-updater
    """
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    """ This is the official name of the product
        For example: NMX-ENC-2412A
        We will only use this name on our site
    """
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    fgs = models.ManyToManyField(FG)
    associated_names = models.ManyToManyField(AssociatedName, blank=True)
    discontinued = models.BooleanField(default=False)
    store_firmware_versions_locally = models.BooleanField(default=True)

    name = models.CharField(max_length=200, unique=True)

    def create_dashless_associated_name(self):
        """Used for search for example DX-TX will create an associated name DXTX"""
        dashless_name = self.name.replace('-', '')
        new_associated_name, _ = AssociatedName.objects.get_or_create(name=dashless_name)
        return new_associated_name

    def save(self, *args, **kwargs):
        product = super().save(*args, **kwargs)
        new_name = self.create_dashless_associated_name()
        self.associated_names.add(new_name)
        return product

    def __str__(self):
        return f"{self.name}"


def upload_path_name(name):
    replacement_list = ['/', ' ', ':', '&', '(', ')']
    for item in replacement_list:
        name = name.replace(item, '-')
    # Remove trailing -
    if name[-1] == '-':
        name = name[:-1]
    # Remove double --
    name.replace('--', '-')
    # Just in case :)
    name.replace('--', '-')
    return name


def upload_location(instance, filename):
    my_path = upload_path_name(instance.name)
    return os.path.join(my_path, filename)


class Version(models.Model):
    """ This is a specific firmware version
    """
    fgs = models.ManyToManyField(FG, blank=True)
    name = models.CharField(max_length=200)
    number = models.CharField(max_length=200)
    download_page = models.CharField(max_length=200, blank=True)
    download_url = models.CharField(max_length=200, blank=True)
    local_file = models.FileField(upload_to=upload_location, max_length=200, null=True, blank=True)
    date_last_seen = models.DateTimeField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    read_me = models.TextField(blank=True)
    read_me_path = models.CharField(max_length=200, blank=True, default="Readme.txt")

    do_not_download = models.BooleanField(default=False)

    hotfix = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.local_file and self.read_me == "":
            self.read_me = self.get_release_notes()
        if self.read_me != "Readme.txt not found...":
            self.get_fgs()
        super().save(*args, **kwargs)

    def get_release_notes(self):
        read_me = "Unable to find readme"
        if not self.read_me_path:
            return "No readme in this firmware"
        possible_encodings = ['utf-8', 'Windows-1252']

        try:
            fh = self.local_file.path
            with ZipFile(fh) as myzip:
                # For SVSi firmware
                for item in myzip.filelist:
                    if 'readme' in item.filename.lower():
                        location = item.filename
                        break
                else:
                    location = self.read_me_path
                with myzip.open(location) as myfile:
                    raw_file = myfile.read()
                    for my_encoding in possible_encodings:
                        try:
                            return raw_file.decode(encoding=my_encoding)
                        except UnicodeDecodeError:
                            pass
                    print(f"Unable to read readme.txt encoding?: {self.name}")
        except KeyError:
            # print(f"Did not find: {self.name}: {self.read_me_path}")
            pass
        except BadZipFile as error:
            print(f"Not a zip file? {self.name}: {error}")
            # If it isn't a zip file just return
            return read_me
        except NotImplementedError as error:
            print(f"Zip error {self.name}: {error}")
            # If we are not able to read the zip file just return
            return read_me
        print(f"Unable to find readme {self.name}")
        return read_me

    def get_fgs(self):
        for fg in FG.objects.all():
            if fg.number in self.read_me:
                self.fgs.add(fg)

    def download_firmware(self):
        # Lets check if we have a local copy first

        with TemporaryFile() as tf:

            # Just get head first
            headers = {'user-agent': 'FirmwareTracker'}
            r = requests.head(self.download_url, headers=headers, allow_redirects=True)

            # Check file length no local copy if it is too big
            if 'content-length' in r.headers:
                if int(r.headers['content-length']) >= settings.FIRMWARE_VERSION_MAX_SIZE:
                    print(f'The version file is too large: {self.name}')
                    return

            filename = os.path.basename(r.url).replace('%20', '_').replace('%2B', '+')
            r = requests.get(self.download_url, headers=headers, stream=True)

            for chunk in r.iter_content(chunk_size=4096):
                tf.write(chunk)
            tf.seek(0)
            self.local_file.save(f"{filename}", File(tf))

    def __str__(self):
        return f"{self.name} v{self.number}"


class Subscriber(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    send_email = models.BooleanField(default=True)
    send_email_even_if_none_found = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user}"

firmware/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import inlineformset_factory

from .models import Subscriber


class ActivateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['is_active']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("email", "first_name", "last_name", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class SubscriberForm(forms.ModelForm):
	class Meta:
		model = Subscriber
		fields = ['send_email', 'send_email_even_if_none_found']
	
class LoginForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ("email", "password")

firmware/templates/firmware/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
 
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

  <link rel="stylesheet" type="text/css" href="{% static 'firmware/css/base.css' %}">

  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'firmware/img/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'firmware/img/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'firmware/img/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'firmware/img/site.webmanifest' %}">


  {% block extra_head %}
  {% endblock %}

  <title>AMX Firmware</title>

</head>
<body>

<div class="container">

{% include 'firmware/navbar.html' %}
{% include 'firmware/messages.html' %}

{% block content %}
{% endblock %}

</div>

</body>



{% block extrajs %}
{% endblock %}

</html>

firmware/templates/firmware/brand_detail.html
{% extends "firmware/base.html" %}

{% block content %}
<h1><a href="{{brand.base_url}}">{{brand.name}}</a></h1>
{% endblock %}

firmware/templates/firmware/brand_list.html
{% extends "firmware/base.html" %}

{% block content %}
    <h2>Brands</h2>
    <ul>
        {% for brand in object_list %}
            <li><a href="{% url 'firmware:brand-detail' brand.id %}">{{ brand }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

firmware/templates/firmware/firmware_detail.html
{% extends "firmware/base.html" %}

{% block content %}

<h1>{{firmware.name}}</h1>
<i>Site: <a href="{% url 'firmware:site-detail' firmware.site.id %}">{{firmware.site}}</a></i>
<h2>Firmware</h2>
<ul>
    {% for version in firmware.version_set.all %}
        <li><a href="{{firmware.site}}{{version.download_page}}">{{version.number}}</a></li>
        {% if firmware.file %}
            <li>{{firmware.file}}</li>
        {% endif %}
    {% endfor %}
</ul>

<h2>Related Products</h2>
    <ul>
        {% for product in firmware.products.all %}
        <li><a href="{% url 'firmware:product-detail' product.id %}">{{ product.name }}</a>
        {% endfor %}
    </ul>


{% endblock %}

firmware/templates/firmware/firmware_list.html
{% extends "firmware/base.html" %}

{% block content %}
    <h2>Firmware</h2>
    <ul>
        {% for firmware in object_list %}
            <li><a href="{% url 'firmware:firmware-detail' firmware.id %}">{{ firmware }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

firmware/templates/firmware/lines.html
{% extends "firmware/base.html" %}

{% block content %}

<style>

</style>
<div class="container">
  <table class="table table-responsive table-hover">
    <thead>
          <tr><th>Column</th><th>Column</th><th>Column</th><th>Column</th></tr>
      </thead>
      <tbody>
          <tr class="clickable" data-toggle="collapse" id="row1" data-target=".row1">
              <td><i class="glyphicon glyphicon-plus"></i></td>
              <td>data</td>
              <td>data</td>  
              <td>data</td>
          </tr>
          <tr class="collapse row1">
              <td>- child row</td>
              <td>data</td>
              <td>data</td>  
              <td>data</td>
          </tr>
          <tr class="collapse row1">
              <td>- child row</td>
              <td>data</td>
              <td>data</td>  
              <td>data</td>
          </tr>
      </tbody>
  </table>
  <style>
  .collapsing {
    -webkit-transition: height .01s ease;
    transition: height .01s ease
  }
  </style>

{% endblock %}

firmware/templates/firmware/messages.html
{% if messages %}
  {% for message in messages %}
  <div class="toast align-items-center show" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="d-flex">
      <div class="toast-body">
        {{ message }}
     </div>
      <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>
  {% endfor %}
{% endif %}

firmware/templates/firmware/navbar.html
<nav class="navbar fixed-top navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'firmware:product-list' %}">Turkish Johnnys</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link {% if active == 'products' %}active{% endif %}" aria-current="page" href="{% url 'firmware:product-list' %}">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if active == 'discontinued' %}active{% endif %}" aria-current="page" href="{% url 'firmware:discontinued-product-list' %}">Discontinued</a>
          </li>
          {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if active == 'register' %}active{% endif %}" aria-current="page" href="{% url 'firmware:register' %}">Sign Up</a>
            </li>
          {% endif %}
          {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/admin">Admin</a>
            </li>
          {% endif %}
        </ul>
        <div class="d-flex" role="search">
          <input id="search-box" title="Searches all products, and all firmware README files" name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search" value="{% if search %}{{search}}{% endif %}">
        </div>
        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle show" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              <i class="bi bi-person-square"></i>
              {% if user.is_authenticated %}
                {{ user.username }}
              {% endif %} 
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown" data-bs-popper="none">
              {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'firmware:profile' %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
              {% else %}
                <li><a class="dropdown-item" href="{% url 'firmware:login' %}">Login</a></li>
              {% endif %} 
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

firmware/templates/firmware/prod_list.html
  <div class="row">
    <div class="col">
      <br>
    </div>
  </div>
  <div class="row g-2">
  {% for product in products %}
      <div class="col col-3 expandable-box {% if product.discontinued %}discontinued-firmware{% else %}current-firmware{% endif %}">
       
        <div class="clickable">
          <span class="product" title="{{ product.name }} {% if product.discontinued %}*Discontinued*{% endif %}">{{ product.name}}</span>
        </div>
        <div class="firmwares hidden">
          <small class="text-left">
            {% for associated_name in product.associated_names.all %}
            {% if forloop.last %}
              {{associated_name}}
            {% else %}
              {{associated_name}},
            {% endif %}
          {% endfor %}
          </small>
          <p>
          {% for fg in product.fgs.all %}
            {% if forloop.last %}
              {{fg}}
            {% else %}
              {{fg}},
            {% endif %}
          {% endfor %}
          </p>
        </div>
        <ul class="list-group firmwares hidden">
          
          {% for version in product.fgs.all.0.version_set.all|dictsortreversed:"number" %}
            {% if not version.hotfix %}
              {% ifchanged version.number %}
                {% include 'firmware/version_item.html' %}
              {% endifchanged %}
            {% endif %}
          {% endfor %}
          {% for version in product.fgs.all.0.version_set.all|dictsortreversed:"number" %}
            {% if version.hotfix %}
              {% ifchanged version.number %}
                {% include 'firmware/version_item.html' %}
              {% endifchanged %}
            {% endif %}
          {% endfor %}
        </ul>
      </div>
    {% empty %}
      <h2>Sorry, no products found....</h2>
    {% endfor %}
    </div>

firmware/templates/firmware/product_detail.html
{% extends "firmware/base.html" %}

{% block content %}
<h1>{{ product.name }}</h1>
<ul>
{% for firmware in product.firmware_set.all %}
<li><a href="{% url 'firmware:firmware-detail' firmware.id %}">{{ firmware }}</a></li>
{% endfor %}
</ul>
{% endblock %}

firmware/templates/firmware/product_list.html
{% extends "firmware/base.html" %}
{% load static %}
{% block content %}
<div class="d-flex justify-content-center">
  <div id="spinner" class="spinner-border spinner" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div>

<div id="products-div" class="text-center">
</div>


{% endblock %}

{% block extrajs %}

<script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>

<script src="{% static 'firmware/js/suggestive_search.js' %}"
  defer
  data-link="{{link}}">
</script>

{% endblock %}

firmware/templates/firmware/subscribe.html
{% extends "firmware/base.html" %}
{% load static %}

{% block extra_head %}
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock %}

{% block content %}

<div class="container">
  {% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>¡Holy guacamole! 🥑</strong><br>
       You should check in on some of those fields below.
      <ul>
        {% for error_field, error_message in form.errors.items %}
            {{ error_message|striptags }}
        {% endfor %}
      </ul>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endif %}
  <br>
  <br>
  <form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_name" class="form-label">Your Name</label>
      <input type="text" name="name" class="form-control" id="id_name" aria-describedby="namelHelp" value="{{ form.name.value|default:'' }}" required>
      <div id="nameHelp" class="form-text">Please enter your name.</div>
    </div>

    <div class="mb-3">
      <label for="id_email" class="form-label">Email address</label>
      <input type="email" name="email" class="form-control" id="id_email" aria-describedby="emailHelp" value="{{ form.email.value|default:'' }}" required>
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
      <div class="g-recaptcha" data-sitekey="{{ sitekey }}"></div>
    </div>
    <button type="submit" value="Submit" class="btn btn-outline-success download-button">Submit</button>
  </form>

</div>

{% endblock %}

{% block extrajs %}
{% if form.errors %}
<script type="text/javascript">
  {% for field in form %}
    var field_input = document.getElementById("{{ field.auto_id }}");
    if (field_input) {
      field_input.classList.add("is-{% if field.errors %}in{% endif %}valid");
    }
  {% endfor %}
</script>  
{% endif %}

{% endblock %}

firmware/templates/firmware/version_item.html
<li title="{% if version.hotfix %}Hotfix Firmware{% else %}Release Firmware{% endif %}" 
  class="list-group-item list-group-item-action flex-column align-items-start list-group-item readme-button
          {% if version.hotfix %}
              list-group-item-warning
          {% else %}
              list-group-item-success
          {% endif %}">
  <div class="d-flex justify-content-between">
    <h5 class="mb-1">{{version.name}} 
      {% if version.hotfix %}
        <i class="bi bi-fire"></i>
      {% else %}
        <i class="bi bi-list-check"></i>
      {% endif %}
    </h5>
    <a href="{{ version.download_page }}" target="_blank" class="btn btn-outline-success download-button">Download <span class="badge rounded-pill bg-secondary">
      {{version.number}} 
      </span>
    </a>
  </div>

  <div class="d-flex justify-content-between">
    <small>Last seen on the website: {{ version.date_last_seen|date:"d-M-Y" }}</small>
      {% if show_local %}
        {% if version.local_file %}
          <a href="{{ version.local_file.url }}" class="btn btn-outline-success download-button m-1">Local Copy</a>
        {% endif %}
      {% endif %}
  </div>

  <div class="d-flex justify-content-between">
    <small> </small>
      {% if show_local %}
         <a href="{% url 'firmware:product-list'%}?link={{product.name}}" class="btn btn-outline-success download-button m-1">Link to page</a>
      {% endif %}
  </div>

  {% if version.read_me %}
    {% if version.read_me != "Unable to find readme" %}
      <textarea class="readme" rows="20">{{version.read_me}}</textarea>
    {% else %}
      <textarea class="readme" rows="1">{{version.read_me}}</textarea>
    {% endif %}
  {% endif %}
</li>

firmware/templates/firmware/version_list.html
{% extends "firmware/base.html" %}
{% load static %}
{% block content %}

<div class="d-flex justify-content-center">
  <div id="spinner" class="spinner-border spinner" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div>

<div id="versions-div" class="text-center">
    {{new_versions}}
</div>


{% endblock %}

{% block extrajs %}

<script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>


{% endblock %}